# Generated by Django 3.0.3 on 2020-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('content', models.CharField(max_length=200, verbose_name='İcerik')),
                ('publishing_date', models.DateTimeField(auto_now=True, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
